eval:
  model_path: "models_mappo/mappo_uav_policy_latest.pt"
  device: "cpu"
  num_missions: 100
  deterministic: true

output:
  results_path: "results/eval_results.json"

drone_settings:
  num_drones: 2
  num_wps_per_drone: 20
