eval_models:
  A2C:
    model_path: "models_a2c_2/a2c_uav_curriculum.zip"
    device: "cuda"

  PPO:
    model_path: "models_ppo_2/ppo_uav_curriculum.zip"
    device: "cuda"

  SAC:
    model_path: "models_sac_2/sac_uav_curriculum_interrupted.zip"
    device: "cuda" # cuda for sac only

eval:
  num_missions: 100

output:
  results_path: "results/eval_results.json"

env: {}

drone_settings:
  num_drones: 2
  num_wps_per_drone: 20
