test:
  device: "cpu"
  model_path: "models_mappo/mappo_uav_policy_latest.pt"
  test_name: "MAPPO"
  mission_mode: "gen_mission"
  save_dir: "reports"
  save_visuals: true
  create_video: true
  show_planned_dubins_paths: false
  deterministic: true
  video_fps: 30
  video_speed: 3

  gen_mission:
    num_drones: 5
    num_waypoints: 20

  missions:
    "UAV-1":
      initial_position: [37.7749, -122.4194]
      initial_heading: 45
      cruise_speed: 25
      turning_radius: 60
      waypoints:
        - - 37.773175
          - -122.420527

    "UAV-2":
      initial_position: [37.7742, -122.4190]
      initial_heading: 270
      cruise_speed: 20
      turning_radius: 55
      waypoints:
        - - 37.774814
          - -122.414403
